export const colleges = [
    "NMAM INSTITUTE OF TECHNOLOGY",
    "CMR INSTITUTE OF TECHNOLOGY, BANGALORE"	,
    "BASAVAKALYANA ENGINEERING COLLEGE, BIDAR"	,
    "EAST POINT COLLEGE OF ENGINEERING, BANGALORE"	,
    "MALNAD COLLEGE OF ENGINEERING"	,
    "TONTADARYA COLLEGE OF ENGINEERING"	,
    "BASAVESHWARA ENGINEERING COLLEGE"	,
    "KLS VISHWANATHRAO DESHPANDE INSTITUTE OF TECHNOLOGY"	,
    "SRINIVAS INSTITUTE OF TECHNOLOGY, VALACHIL"	,
    "SAMBHRAM INSTITUTE OF TECHNOLOGY, BANGALORE"	,
    "NEW HORIZON COLLEGE OF ENGINEERING, BANGALORE"	,
    "MYSORE COLLEGE OF ENGINEERING AND MANAGEMENT"	,
    "ADARSHA INSTITUTE OF TECHNOLOGY, BANGALORE"	,
    "CAUVERY INSTITUTE OF TECHNOLOGY, MANDYA"	,
    "REVA UNIVERSITY, BANGALORE"	,
    "KVG COLLEGE OF ENGINEERING"	,
    "ADHICHUNCHUNAGIRI INSTITUTE OF TECHNOLOGY"	,
    "MAHARAJA INSTITUTE OF TECHNOLOGY"	,
    "ANGADI INSTITUTE OF TECHNOLOGY AND MANAGEMENT, BELGAUM"	,
    "ACS COLLEGE OF ENGINEERING, BANGALORE"	,
    "VIJAYA VITTALA INSTITUTE OF TECHNOLOGY, BANGALORE"	,
    "AKSHAYA INSTITUTE OF TECHNOLOGY, TUMKUR"	,
    "SRI SIDDARTHA INSTITUTE OF TECHNOLOGY"	,
    "SIDDAGANGA INSTITUTE OF TECHNOLOGY"	,
    "BMS INSTITUTE OF TECHNOLOGY AND MANAGEMENT"	,
    "VIVEKANANDA COLLEGE OF ENGINEERING AND TECHNOLOGY"	,
    "RAGIV GANDHI INSTITUTE OF TECHNOLOGY"	,
    "NIT TRICHY"	,
    "PES COLLEGE OF ENGINEERING, MANDYA"	,
    "SRI JAYACHAMARAJENDRA COLLEGE OF ENGINEERING, JSSTI CAMPUS, MYSORE"	,
    "THE NATIONAL INSTITUTE OF ENGINEERING MANSNDAVADI, MYSORE"	,
    "MALNAD COLLEGE OF ENGINEERING, HASSAN"	,
    "RAMAIAH UNIVERSITY OF APPLIED SCIENCE, BANGALORE"	,
    "SRI VINAYAKA INSTITUTE OF TECHNOLOGY"	,
    "MYSURU ROYAL INSTITUTE OF TECHNOLOGY"	,
    "DAYANAND SAGAR UNIVERSITY, BANGALORE"	,
    "KLE TECHNOLOGICAL UNIVERSITY"	,
    "SRI DHARMASTHA MANJUNATHESHWARA COLLEGE OF ENGINEERING"	,
    "ANJUMAN ENGINEERING COLLEGE"	,
    "K.L.E.DR.M S SHESHAGIRI COLLEGE OF ENGINEERING AND TECHNOLOGY"	,
    "B.L.D.E.A'S V.P.DR.P.G.HALLAKATTI COLLEGE OF ENGINEERING AND TECHNOLOGY"	,
    "SRI TARALABALU JAGADGURU INSTITUTE OF TECHNOLOGY"	,
    "R.V. COLLEGE OF ENGINEERING, BANGALORE"	,
    "BMS COLLEGE OF ENGINEERING, BANGALORE"	,
    "UNIVERSITY VISVESWARAIAH COLLEGE OF ENGINEERING, BANGALORE"	,
    "DR. AMBEDKAR INSTITUTE OF TECHNOLOGY, BANGALORE"	,
    "B.V.B, HUBLI"	,
    "BMS ARCHITECTURE, BANGALORE"	,
    "NIE MYSORE"	,
   " BITS PILANI, GOA"	,
    "STJ INSTITUTE OF TECHNOLOGY, RANEBENNUR"	,
    "JAIN INSTITITE OF TECHNOLOGY, DAVANGERE"	,
    "BALLARI INSTITUTE OF TECHNOLOGY AND MANAGEMENT"	,
    "AMRUTHA INSTITUTE OF ENGINEERING, BENGALURU"	,
    "APS COLLEGE OF ENGINEERING"	,
    "BTL INSTITUTE OF TECHNOLOGY AND MANAGEMENT",	
    "DSCE KANKPUR, BANGALORE"	,
    "G MADEGOWDA INSTITUTE OF TECHNOLOGY, MANDYA"	,
    "H K B K COLLEGE OF ENGINEERING, BANGALORE"	,
    "SHRINIVAS COLLEGE OF ENGINEERING, MUKKA"	,
    "NDRK INSTITUTE OF TECHNOLOGY"	,
    "GOVERNMENT ENGINEERING COLLEGE, HASSAN"	,
    "S.E.A COLLEGE OF ENGINEERING"	,
    "HKE'S SLN COLLEGE OF ENGINEERING (HKES), RAICHUR"	,
    "PNSIT"	,
    "Sha Shib college of Engineering"	,
    "Sheikh college of engineering"	,
    "Byre Gowda Institute of technology"	,
    "NIE Institute of Technology"	,
    "JIT"	,
    "AGM Rural Engineering College"	,
    "Gopalan college of Engineering and Management"	,
    "Sampoorna Institute of Technology"	,
    "K.S. School of Engineering and Management"	,
    "Bangalore Technological Institute,Kodathi"	,
    "ATME College of engineering,Mysore"	,
    "Achuttha Institute of Technology"	,
    "Jyothi Institute of Technology"	,
    "Jain Institute Technology"	,
    "Dayananda Sagar Academy of Technology"	,
    "Lingarajappa Engineering College"	,
    "Shetty Institute of Technology"	,
    "Girijabal Sail Institute of Technology"	,
    "SJB Institute of Technology"	,
    "R.L. Jalappa Institute of Technology"	,
    "Alpha College of Engineering"	,
    "RNS Institute of Technology"	,
    "KCT Engineering College"	,
    "Cambridge Institute of Technology Basavanapura,Bangalore"	,
    "PES Institute of Technology and management,Shivamoga"	,
    "SDM Institute of Technology,ujire"	,
    "S.E.A College of Engineeringand Technology,Bangalore"	,
    "Government Engineering College,Chamrajnagar"	,
    "Government Engineering College,Hassan"	,
    "Government Engineering College,Mandya"	,
    "Sri Sai Ram College of Engineering"	,
    "Sapthagiri"	,
    "East West Institute of Technology"	,
    "NM Institute of Technology"	,
    "BNM Istitute of Technology"	,
    "City Engineering"	,
    "Sri Venkateshwara"	,
    "Channabasaweshwara Institute of Technology"	,
    "Global Academy of Technology"	,
    "Nagarjuna College of Enginnering and Technology"	,
    "Rao Bahadur Engineering College,Bellary"	,
    "PDA College of Engineering,Gulbarga	",
    "Bheemanna Khandre Institute of Technology,Bidar"	,
    "Hirasagar Institute of Technology,Belagavi"	,
    "Khaja Banda Nawaz college of Engineering,Gulbarga"	,
    "BGMIT MUDHOL"	,
    "M.S RAMAIAH INSTITUTE OF TECHNOLOGY, BANGALORE",
    "RV COLLEGE OF ENGINEERING"
    
] 