export const persons = [
  {
    name: "RITHESH BEKAL",
    role: "COORDINATOR",
    img: "/team/Rithesh.png",
    email: "rithesh13bekal@gmail.com",
    mob: "9620004763",
  },

  {
    name: "RAMSHRAVAN RAI",
    role: "CO-COORDINATOR",
    img: "/team/RAM.png",
    email: "ramshravan222@gmail.com",
    mob: "8660305851",
  },
  {
    name: "SHRIVIDYA POOJARY",
    role: "CO-COORDINATOR",
    img: "/team/Srividya.png",
    email: "shrividya2k@gmail.com",
    mob: "9663312695",
  },
  {
    name: "VIJETH ULLAL",
    role: "CULTURAL COORDINATOR",
    img: "/team/Vijeth.png",
    email: "vijethula1402@gmail.com",
    mob: "9480565835",
  },
  {
    name: "VINAY SAMANTRI",
    role: "HEAD OF DIGITAL & TECHNICAL COMMITTIEES",
    img: "/team/Vinay.png",
    email: "vinis05072000@gmail.com",
    mob: "7760610521",
  },
  {
    name: "ABHIJNAN PRAKASH",
    role: "HEAD OF SPONSORSHIP COMMITTEE",
    img: "/team/Abhi.png",
    email: "abhijnanprakash@gmail.com",
    mob: "8095628046",
  },
  {
    name: "BHARATH M KULKARNI",
    role: "HEAD OF HOSPITALITY, VALEDICTORY & TECHNICAL COMMITTEES",
    img: "/team/Bharat.png",
    email: "bharathmkulkarni@gmail.com",
    mob: "886185124",
  },
  {
    name: "SUSHAAN K ATTAVAR",
    role: "HEAD OF RE & STAGE COMMITTEES",
    img: "/team/sushan.png",
    email: "sushattavar@gmail.com",
    mob: "9886383777",
  },

  {
    name: "ARADHANA NAMBIAR",
    role: "HEAD OF PUBLICITY COMMITTEE",
    img: "/team/Aradhana.png",
    email: "andanambiar3@gmail.com",
    mob: "9148275419",
  },
  {
    name: "WAYNE DSOUZA",
    role: "HEAD OF SOCIAL MEDIA & DOCUMENTATION COMMITTEES",
    img: "/team/Wayne.png",
    email: "waynereuben03@gmail.com",
    mob: "8971491645",
  },
  {
    name: "MOGHE SUDHEESH RAO",
    role: "HEAD OF INAUGURAL & STAGE COMMITTEES",
    img: "/team/Sudheesh.png",
    email: "raosudheesh12@gmail.com",
    mob: "9902145643",
  },
  {
    name: "DEEKSHITHA SHETTY",
    role: "HEAD OF PUBLICITY COMMITTEE",
    img: "/team/Deeks.png",
    email: "shettydeekshita15@gmail.com",
    mob: "9686693372",
  },
  {
    name: "SHRAVYA JAIN",
    role: "HEAD OF RE",
    img: "/team/Shravya.png",
    email: "shravya7@gmail.com",
    mob: "9482254166",
  },

  {
    name: "ROLAN GOMES",
    role: "HEAD OF DIGITAL COMMITTEE",
    img: "/team/rolan_.png",
    email: "rolangomes19@gmail.com",
    mob: "9019536394",
  },
  {
    name: "MANAS M RAI",
    role: "HEAD OF RE & STAGE COMMITTEES",
    img: "/team/manas.png",
    email: "manasrai9611@gmail.com",
    mob: "9611543935",
  },
  {
    name: "ADITYA BHAT",
    role: "HEAD OF JURY COMMITTEE",
    img: "/team/ADB.png",
    email: "madibhat@gmail.com",
    mob: "9611309109",
  },
  {
    name: "NIHAL SHETTY",
    role: "HEAD OF MEDIA COMMITTEE",
    img: "/team/Nihal.png",
    email: "nihalvshetty18@gmail.com",
    mob: "9611285768",
  },

  {
    name: "SHREESHA SHETTY",
    role: "HEAD OF RE",
    img: "/team/Shreesha.png",
    email: "Shreesha12129@gmail.com",
    mob: "9686596283",
  },
  {
    name: "ANUP RAI",
    role: "HEAD OF TRANSPORTATION COMMITTEE",
    img: "/team/Anup.png",
    email: "anupashokshetty@gmail.com",
    mob: "9945191271",
  },
  {
    name: "RAHUL BHAT",
    role: "HEAD OF TECHNICAL COMMITTEE",
    img: "/team/Rahul.png",
    email: "rahulbhat0201@gmail.com",
    mob: "8951838121",
  },
  {
    name: "PRAVEEN DEVADIGA",
    role: "ADVISER",
    img: "/team/Praveen.png",
    email: "rithesh13bekal@gmail.com",
    mob: "9663094655",
  },
  {
    name: "PREM DEVADIGA",
    role: "ADVISER",
    img: "/team/Prem.png",
    email: "rithesh13bekal@gmail.com",
    mob: "8197883206",
  },
];
